//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 06:03:02 PM MSK 
//


package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.bussines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CaseNumber" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0}string-100" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="ServiceOrFunction" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0}ServiceOrFunctionType"/>
 *           &lt;element name="ServiceOrFunctionCode" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0}string-50"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseInfoType", propOrder = {
    "caseNumber",
    "serviceOrFunction",
    "serviceOrFunctionCode"
})
public class CaseInfoType {

    @XmlElement(name = "CaseNumber")
    protected String caseNumber;
    @XmlElement(name = "ServiceOrFunction")
    protected ServiceOrFunctionType serviceOrFunction;
    @XmlElement(name = "ServiceOrFunctionCode")
    protected String serviceOrFunctionCode;

    /**
     * Gets the value of the caseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseNumber(String value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the serviceOrFunction property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceOrFunctionType }
     *     
     */
    public ServiceOrFunctionType getServiceOrFunction() {
        return serviceOrFunction;
    }

    /**
     * Sets the value of the serviceOrFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceOrFunctionType }
     *     
     */
    public void setServiceOrFunction(ServiceOrFunctionType value) {
        this.serviceOrFunction = value;
    }

    /**
     * Gets the value of the serviceOrFunctionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceOrFunctionCode() {
        return serviceOrFunctionCode;
    }

    /**
     * Sets the value of the serviceOrFunctionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceOrFunctionCode(String value) {
        this.serviceOrFunctionCode = value;
    }

}
