//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 06:03:02 PM MSK 
//


package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.bussines;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.voskhod.smev.client.autogenerated.bussines package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Frgu_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0", "frgu");
    private final static QName _CaseInfo_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0", "CaseInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.voskhod.smev.client.autogenerated.bussines
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CaseInfoType }
     * 
     */
    public CaseInfoType createCaseInfoType() {
        return new CaseInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0", name = "frgu")
    public JAXBElement<String> createFrgu(String value) {
        return new JAXBElement<String>(_Frgu_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0", name = "CaseInfo")
    public JAXBElement<CaseInfoType> createCaseInfo(CaseInfoType value) {
        return new JAXBElement<CaseInfoType>(_CaseInfo_QNAME, CaseInfoType.class, null, value);
    }

}
