//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.10 at 06:03:02 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/business-process-metadata/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.bussines;
