
package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated;

import javax.xml.ws.WebFault;
import com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.types.fault.BusinessDataTypeIsNotSupported;


/**
 * 
 *                     Запрос с таким полным именем корневого элемента не зарегистрирован в СМЭВ (см. //SendRequestRequest/MessagePrimaryContent/element()).
 *                     Вероятные причины:
 *                     ошибка при формировании содержательной части запроса (см. //SendRequestRequest/MessagePrimaryContent/element());
 *                     запрос этого типа ещё не зарегистрирован в СМЭВ.
 *                 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BusinessDataTypeIsNotSupported", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")
public class BusinessDataTypeIsNotSupportedException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessDataTypeIsNotSupported faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessDataTypeIsNotSupportedException(String message, BusinessDataTypeIsNotSupported faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessDataTypeIsNotSupportedException(String message, BusinessDataTypeIsNotSupported faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.types.fault.BusinessDataTypeIsNotSupported
     */
    public BusinessDataTypeIsNotSupported getFaultInfo() {
        return faultInfo;
    }

}
