
package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated;

import javax.xml.ws.WebFault;
import com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.types.fault.DestinationOverflow;


/**
 * 
 *                     Очередь, в которую должен быть послано сообщение, переполнена.
 *                     Действия клиента: обратиться в службу техподдержки СМЭВ, и продолжать посылать запрос повторно, до успеха.
 *                 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "DestinationOverflow", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")
public class DestinationOverflowException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DestinationOverflow faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DestinationOverflowException(String message, DestinationOverflow faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DestinationOverflowException(String message, DestinationOverflow faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated.types.fault.DestinationOverflow
     */
    public DestinationOverflow getFaultInfo() {
        return faultInfo;
    }

}
