/**
 * 
 *         Веб-сервис, предоставляемый СМЭВ, через который
 *         все участники межведомственного взаимодействия обмениваются сообщениями.
 *     
 * 
 */
package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated;
