
package com.integriks.smev.nwxRewrite.client.src.serverApi.autogenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SMEVMessageExchangeService", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1", wsdlLocation = "file:/C:/Root/source/client-2015/server-api/xml-artifacts/transport-service/1.1/smev-message-exchange-service-1.1.wsdl")
public class SMEVMessageExchangeService
    extends Service
{

    private final static URL SMEVMESSAGEEXCHANGESERVICE_WSDL_LOCATION;
    private final static WebServiceException SMEVMESSAGEEXCHANGESERVICE_EXCEPTION;
    private final static QName SMEVMESSAGEEXCHANGESERVICE_QNAME = new QName("urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1", "SMEVMessageExchangeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Root/source/client-2015/server-api/xml-artifacts/transport-service/1.1/smev-message-exchange-service-1.1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMEVMESSAGEEXCHANGESERVICE_WSDL_LOCATION = url;
        SMEVMESSAGEEXCHANGESERVICE_EXCEPTION = e;
    }

    public SMEVMessageExchangeService() {
        super(__getWsdlLocation(), SMEVMESSAGEEXCHANGESERVICE_QNAME);
    }

    public SMEVMessageExchangeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SMEVMessageExchangePortType
     */
    @WebEndpoint(name = "SMEVMessageExchangeEndpoint")
    public SMEVMessageExchangePortType getSMEVMessageExchangeEndpoint() {
        return super.getPort(new QName("urn://x-artefacts-smev-gov-ru/services/message-exchange/1.1", "SMEVMessageExchangeEndpoint"), SMEVMessageExchangePortType.class);
    }

    private static URL __getWsdlLocation() {
        if (SMEVMESSAGEEXCHANGESERVICE_EXCEPTION!= null) {
            throw SMEVMESSAGEEXCHANGESERVICE_EXCEPTION;
        }
        return SMEVMESSAGEEXCHANGESERVICE_WSDL_LOCATION;
    }

}
